name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY_NAME: hexletbasics
  IS_PUSH: ${{ github.event_name == 'push' }}
  COLOR_MAP: '{ success: "#800000", failure: "#008000" }'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Set image name
        run: |
          echo "IMAGE_NAME=${{ env.REGISTRY_NAME }}/$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.IS_PUSH == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          cache-to: type=inline
          tags: |
            ${{ env.IMAGE_NAME }}:cached

      - uses: actions/checkout@v2

      - name: Check
        run: |
          docker-compose --file docker-compose.yml up --abort-on-container-exit

      - name: Push
        if: ${{ env.IS_PUSH == 'true' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Send notification into Slack
        if: ${{ always() && env.IS_PUSH == 'true' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ fromJson(env.COLOR_MAP)[job.status] }}
          SLACK_TITLE: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
